apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: task5acr85666f.azurecr.io/backend:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          # Health probes
          livenessProbe:
            httpGet:
              path: /api/health-liveness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health-readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /api/health-startup
              port: 3000
            failureThreshold: 30
            periodSeconds: 10